### PR TITLE
General compatibility and multiple bug fixes.

### PR DESCRIPTION
**Pull request by ClementPadovani**

### CODE REVIEW

**Comment by markohlebar** [comment]
@ClementPadovani wow thanks! I'll check this tomorrow and make a merge :)

**Comment by ClementPadovani** [comment]
@markohlebar alright! Keep me posted :)

**Comment by markohlebar** [comment]
Hey @ClementPadovani, it seems that the tests are broken on Peckham target, can you take a peek? I need to put this on Travis.

**Comment by ClementPadovani** [comment]
Alright will do when I get back home. 

Thanks, Clément

**Comment by ClementPadovani** [comment]
Oh yeah @markohlebar, I forgot that I couldn't run the tests because there seems to be some issues with the Kiwi library. There are issues with it overriding the `description` property and most of all it's using the SenTesting Framework which is deprecated.

Could we chat privately?

**Comment by ClementPadovani** [comment]
@markohlebar I got the tests up and working!

Please check out https://github.com/ClementPadovani/Peckham/commit/b358fd07ff99fe72801669d71bca22cd09234fc2

**Comment by ClementPadovani** [comment]
@markohlebar I got the tests running however they seem to be failing at the moment.

[CI Status](https://travis-ci.org/ClementPadovani/Peckham)

https://travis-ci.org/ClementPadovani/Peckham

However they seem to be running fine when I run them from Xcode. I'll check it out.

**Comment by markohlebar** [comment]
Hey @ClementPadovani I get a `cp: 2/MHImportBusterTests/TestFiles/: No such file or directory` build error when I'm running tests agains `Peckham`, do you get that?

**Comment by markohlebar** [comment]
Granted I'm getting that on ` 7.0 beta 4 (7A165t)` which doesn't matter if the build is finr on `6.4`

**Comment by ClementPadovani** [comment]
@markohlebar hum weird, I'm running Xcode 7.0 beta too (same build) and I don't get that.

Did you try doing a full clean?

Can you post the build log?

**Pull request merged**
