### PR TITLE
Updated .travis.yml

### PR DESCRIPTION
**Pull request by ClementPadovani**
Updated `.travis.yml` to use Xcode 7.

### CODE REVIEW

**Comment by markohlebar** [comment]
@ClementPadovani there is something seriously messed up with the tests or something. Need to check that out.

**Comment by markohlebar** [comment]
I tried xit-ing the failing test and it still craps out :(

**Comment by ClementPadovani** [comment]
@markohlebar The tests work some of the time actually lol

**Comment by ClementPadovani** [comment]
Actually it’s xctool that’s crashing

**Pull request closed without merging**
