### PR TITLE
support XCode6.2

### PR DESCRIPTION
**Pull request by bumaociyuan**

### CODE REVIEW

**Comment by GSMonster** [comment]
still can't run for Xcode6.2

**Comment by bumaociyuan** [comment]
@GSMonster delete plugin at plugin folder then build again

**Comment by GSMonster** [comment]
How to delete the plugin?

**Comment by bumaociyuan** [comment]
@GSMonster 
```
rm ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin
```

**Comment by GSMonster** [comment]
I have deleted the plugin,but when I run ,it still crash ,why?

**Comment by bumaociyuan** [comment]
No idea....

**Comment by markohlebar** [comment]
@bumaociyuan thanks for that! 
@GSMonster the PR was merged now so it should work.

**Pull request merged**
